import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "./_components/sidebar/sidebar";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "auto",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="flex h-full">
          <Sidebar />
          <main className="ml-64 min-w-0 flex-1">{children}</main>
        </div>
        <Toaster richColors visibleToasts={5} expand={true} position="top-center"/>
      </body>
    </html>
  );
}
